controller_manager:
  ros__parameters:
    update_rate: 30  # Hz
    # use_sim_time: true  # Gazebo plugin automatically sets this

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 50.0

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']

    # Match URDF dimensions
    wheel_separation: 0.35   # wheel_ygap(0.175) * 2
    wheel_radius: 0.05

    # Enable odometry TF publishing
    enable_odom_tf: true

    base_frame_id: base_link

joint_broad:
  ros__parameters:
    use_sim_time: true
